### ISSUE TITLE
Abwechselnd Lang1 <-> Lang2

### ISSUE THREAD

**Issue by LvckyAPI** [LvckyWorld/Vokabeltrainer#1]
## User Story:
Akutell wurde von @CodingTrashpanda eingestellt, das ausschließlic von Deutsch zu anderen Sprache überstezt werden kann. Wir wollen, das wir von Deutsch zur Anderen, und von der Anderen zur deustchen sprache zufällig überstetzen müssen.

## Referenz:
- [Code](https://github.com/LvckyWorld/Vokabeltrainer/blob/4f0e971ecf38bf40b1e3fe29ce0de3238d69548e/Vokabeltrainer.cpp#L84)

## ToDo:
- [ ] code genauer analysieren & kommentieren
- [ ] möglichkeit schaffen, zufällig zwischen **deu -> other** und **other -> deu** zu wechseln 
- [ ] bei gelegenheit Code verbessern und kommentieren
- [ ] bei Erfolg Pull-Request zum original-repo

## Wichtig:
- [ ] Nach abschluss Label https://github.com/LvckyWorld/Vokabeltrainer/labels/status%20-%20needs%20review anfügen und in den main pushen lassen
- [ ] Prüfen ob Pull request für @CodingTrashpanda sinnvoll ist
